//! Axiom Engram - Persistent experience-based memory system
//!
//! Three layers:
//! - Episodic: direct experiences, on-device, user-owned
//! - Semantic: abstractions distilled nightly
//! - Imagined: generated by imagination engine, quarantined from real engrams
//!
//! ## Architecture
//!
//! ```text
//! L1: QemCache (holographic XOR codes, write-through)
//! L2: EngramStore (SQLCipher, FTS5, vector search)
//! L3: ContextAssembler (owns retrieval, token-budgeted assembly)
//! ```
//!
//! All layers implement `MemoryBackend`, so callers can work against the trait
//! and swap implementations without code changes.

pub mod sync;
pub mod adapter;
pub mod schema;
pub mod store;
pub mod engram;
pub mod entry;
pub mod r#trait;
pub mod qem;
pub mod embed;
pub mod noise;

pub use engram::{Engram, EngramLayer, EngramSource, EngramLink, PrivacyLevel, CoherenceState, CharacterTopology, Goal, GoalStatus, ConsolidationRun, LinkType};
pub use store::EngramStore;
pub use store::LinkInferenceConfig;
pub use store::TemporalPattern;
pub use store::WriteOutcome;
pub use store::NearDuplicate;
pub use store::QuarantineFilter;
pub use schema::create_tables;
pub use schema::migrate;
pub use entry::{MemoryEntry, MemoryId, MemoryLayer, MemoryScope, ContentType, MemorySource, MemoryLink, EvidenceRef};
pub use r#trait::{MemoryBackend, Query, SortKey, DecayReport, ConsolidationReport};
pub use qem::{QemCache, QemConfig, QemCode, QemEncoder, NoveltyFilter};
pub use adapter::EngramStoreAdapter;
pub use embed::{Embedder, NoopEmbedder, should_embed, generate_embeddings_batch};
#[cfg(feature = "onnx-embed")]
pub use embed::OnnxEmbedder;
pub use thiserror::Error;

/// Local hex encoding — deliberately avoids pulling in the `hex` crate.
pub(crate) mod hex {
    pub fn encode(bytes: impl AsRef<[u8]>) -> String {
        bytes.as_ref().iter().map(|b| format!("{:02x}", b)).collect()
    }
}

#[derive(Error, Debug)]
pub enum EngramError {
    #[error("Database error: {0}")]
    Database(#[from] rusqlite::Error),
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
}

/// Result type for engram operations
pub type Result<T> = std::result::Result<T, EngramError>;
